services:
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: tipbot-prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.4.0
    container_name: tipbot-grafana
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana-dev-data:/var/lib/grafana
      - ./grafana:/etc/grafana
    networks:
      - monitoring
    restart: unless-stopped

  loki:
    image: grafana/loki:3.3.2
    container_name: tipbot-loki
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki-data:/loki
    ports:
      - "127.0.0.1:3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - monitoring
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.3.2
    container_name: tipbot-promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro       
      - /var/log:/var/log:ro                               
      - /var/lib/docker/containers:/var/lib/docker/containers:ro  
      - ./promtail-config.yaml:/etc/promtail/config.yml:ro
      - promtail-positions:/tmp
    ports:
      - "127.0.0.1:9080:9080"
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring
    depends_on:
      - loki
    restart: unless-stopped

networks:
  monitoring:
    external: true   

volumes:
  grafana-dev-data:
  loki-data:
  promtail-positions: